# Generated by Django 5.1.5 on 2025-01-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0007_remove_truckdriver_check_in_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckdriver',
            old_name='truck_number',
            new_name='dot_number',
        ),
    ]
