# Generated by Django 5.1.5 on 2025-05-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0008_rename_truck_number_truckdriver_dot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdriver',
            name='dot_number',
        ),
    ]
