# Generated by Django 5.1.5 on 2025-05-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0009_remove_truckdriver_dot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('total_tests', models.IntegerField(default=0)),
                ('tests_remaining', models.IntegerField(default=0)),
            ],
        ),
    ]
