# Generated by Django 5.1.5 on 2025-05-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0010_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckdriver',
            old_name='company',
            new_name='company_name',
        ),
    ]
