# Generated by Django 5.1.5 on 2025-05-30 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0011_rename_company_truckdriver_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waitapp.company'),
        ),
    ]
