# Generated by Django 5.1.5 on 2025-05-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0012_truckdriver_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckdriver',
            name='company_name',
        ),
    ]
