# Generated by Django 5.1.5 on 2025-05-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0013_remove_truckdriver_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdriver',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
