# Generated by Django 5.1.5 on 2025-07-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0014_alter_truckdriver_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
