# Generated by Django 5.1.5 on 2025-07-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0015_alter_company_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truckdriver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
