# Generated by Django 5.1.5 on 2025-07-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitapp', '0017_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdriver',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
